package artifact

import (
	"path"
	"slices"
	"strings"
)

// Category constants. The set is intentionally small and descriptive
// rather than evaluative — "looks like build glue" is a path fact,
// not a verdict. The synthesist takes these as inputs to its trust
// reasoning; the classifier's job is to surface the same evidence
// the way a human reviewer would naturally bucket it.
//
// Adding a new category is cheap; renaming one is a wire-format
// change because Categories is a map keyed by these strings.
const (
	CategoryBuildGlue      = "build_glue"
	CategoryGenerated      = "generated"
	CategoryVendored       = "vendored"
	CategoryBinaryInTests  = "binary_in_tests"
	CategorySuspiciousPath = "suspicious_path"
	CategoryOther          = "other"
)

// classify returns the category bucket for a tarball path. Header-
// only — no content reads, no magic-byte sniffing. Suspicious-path
// detection is deliberately first so a "../foo.m4" surfaces as
// suspicious_path rather than build_glue: the path-shape problem
// outranks the file-type problem.
//
// Order of checks:
//
//  1. suspicious_path  — wins over everything; a bad path is the
//     headline regardless of what filename comes after it.
//  2. generated        — autoconf/automake outputs by exact name.
//  3. vendored         — under vendor/ third_party/ deps/.
//  4. build_glue       — m4 / autotools sources / lifecycle scripts.
//  5. binary_in_tests  — under tests/testdata/fixtures with a
//     binary-shaped extension. Header-only means we can't verify
//     the bytes; the path shape is the heuristic.
//  6. other            — fallback.
func classify(p string) string {
	if isSuspiciousPath(p) {
		return CategorySuspiciousPath
	}
	if isGenerated(p) {
		return CategoryGenerated
	}
	if isVendored(p) {
		return CategoryVendored
	}
	if isBuildGlue(p) {
		return CategoryBuildGlue
	}
	if isBinaryInTests(p) {
		return CategoryBinaryInTests
	}
	return CategoryOther
}

// isSuspiciousPath returns true for paths that escape an
// extraction root or otherwise look unfit for filesystem
// materialisation. Walker preserves them verbatim; classifier
// flags them so the synthesist sees the path-shape concern as a
// first-class category rather than buried inside "other".
func isSuspiciousPath(p string) bool {
	if p == "" {
		return false
	}
	if strings.HasPrefix(p, "/") {
		return true
	}
	if strings.Contains(p, "\x00") {
		return true
	}
	// Any "../" component, anywhere in the path, escapes the
	// extraction root. path.Clean would normalize it away — we
	// want the pre-clean detection so legitimate paths with
	// embedded ".." (none, in practice) stay distinguishable.
	return slices.Contains(strings.Split(p, "/"), "..")
}

// generatedFileBasenames lists exact-match autoconf / automake
// outputs that appear in a release tarball but typically NOT in the
// git tree (they're produced by `autoreconf` at dist-prep time).
// Not exhaustive — additions land here when dogfood traces show a
// healthy project being mis-categorised as build_glue or other.
var generatedFileBasenames = map[string]struct{}{
	"configure":     {},
	"config.guess":  {},
	"config.sub":    {},
	"config.status": {},
	"depcomp":       {},
	"install-sh":    {},
	"missing":       {},
	"compile":       {},
	"ltmain.sh":     {},
	"ylwrap":        {},
	"test-driver":   {},
	"py-compile":    {},
	"mkinstalldirs": {},
	"texinfo.tex":   {},
	"INSTALL":       {}, // autoconf-shipped boilerplate
}

func isGenerated(p string) bool {
	base := path.Base(p)
	if _, ok := generatedFileBasenames[base]; ok {
		return true
	}
	// *.in templates produced from .am sources are autotools dist
	// artifacts; aclocal.m4 is generated by aclocal but lives next
	// to the hand-written *.m4 macros, so it gets its own special-case.
	if base == "aclocal.m4" {
		return true
	}
	if strings.HasSuffix(base, ".in") {
		return true
	}
	return false
}

// vendoredPrefixes are conventional roots for third-party code that
// gets copied into the source tree. Match by leading path component
// so "vendor/foo" hits but "src/vendor.go" doesn't.
var vendoredPrefixes = []string{
	"vendor/",
	"third_party/",
	"third-party/",
	"deps/",
	"node_modules/",
}

func isVendored(p string) bool {
	for _, prefix := range vendoredPrefixes {
		if strings.HasPrefix(p, prefix) {
			return true
		}
	}
	return false
}

// buildGlueExtensions and buildGlueBasenames cover hand-written
// build-system inputs — the surface where an attacker who controls
// the dist-prep step can inject runtime behaviour into ./configure.
//
// *.m4 is the headline: the xz attack shipped its payload as
// build-to-host.m4. Generated *.in templates are excluded by the
// generated-check running first.
var buildGlueExtensions = map[string]struct{}{
	".m4": {},
	".am": {},
	".ac": {},
}

var buildGlueBasenames = map[string]struct{}{
	"configure.ac":      {},
	"configure.in":      {}, // older autoconf form, NOT a generated *.in
	"Makefile.am":       {},
	"setup.py":          {},
	"setup.cfg":         {},
	"pyproject.toml":    {},
	"build.rs":          {},
	"binding.gyp":       {},
	"CMakeLists.txt":    {},
	"meson.build":       {},
	"meson_options.txt": {},
	"BUILD":             {},
	"BUILD.bazel":       {},
	"WORKSPACE":         {},
}

func isBuildGlue(p string) bool {
	base := path.Base(p)
	if _, ok := buildGlueBasenames[base]; ok {
		return true
	}
	ext := path.Ext(base)
	if _, ok := buildGlueExtensions[ext]; ok {
		return true
	}
	return false
}

// testRootPrefixes mark paths inside conventional test-fixture
// directories. Combined with binaryishExtensions to flag the xz
// "test data that isn't test data" pattern: the malicious payload
// shipped as tests/files/*.{xz,lzma}.
var testRootPrefixes = []string{
	"tests/",
	"test/",
	"testdata/",
	"fixtures/",
	"__fixtures__/",
}

var binaryishExtensions = map[string]struct{}{
	".xz":    {},
	".lzma":  {},
	".gz":    {},
	".bz2":   {},
	".zst":   {},
	".tar":   {},
	".zip":   {},
	".7z":    {},
	".bin":   {},
	".so":    {},
	".dll":   {},
	".dylib": {},
	".o":     {},
	".a":     {},
}

func isBinaryInTests(p string) bool {
	inTestRoot := false
	for _, prefix := range testRootPrefixes {
		if strings.HasPrefix(p, prefix) {
			inTestRoot = true
			break
		}
	}
	if !inTestRoot {
		return false
	}
	_, ok := binaryishExtensions[path.Ext(p)]
	return ok
}
